FROM yg397/social-network-microservices:latest

RUN apt install -y python3
RUN apt install -y python3-pip
RUN python3 -m pip install pyyaml

COPY scripts/config.py /social-network-microservices/scripts/config.py